### ISSUE TITLE
Add `dlsVerified` to pharmacy divisions

### ISSUE THREAD

**Issue by svetavedmed** [edenlabllc/ehealth.api#4553] opened 2019-03-25 22:19 UTC
dlsVerified is globally added to divisions, but is used only for pharmacy divisions

- add dlsVerified
- add dlsId
- add filter by dlsVerified

**Comment by progsmile** [comment] 2019-03-27 09:33
Duplicate of #4575

**Closed by progsmile** 2019-03-27 09:33 UTC
Labels: BE, [zube]: To Do, epic/nhs_admin_portal_v2
