### ISSUE TITLE
Division is null in response on Get Contracts list, PROD, #J1076

### ISSUE THREAD

**Issue by AlekzandrV** [edenlabllc/ehealth.api#4704] opened 2019-04-05 13:28 UTC
See logs in related support ticket

**Comment by kiurchv** [comment] 2019-04-10 14:02
Such a response is returned when one of the contractor divisions is inactive.
It seems that we can deactivate division even when there are active contracts it acting in existing

**Comment by svetavedmed** [comment] 2019-05-22 14:11
current response is according realization. In case it should be changed service request should be created. Ticked closed as this is not a bug.

**Closed by svetavedmed** 2019-05-22 14:11 UTC
Labels: BE, [zube]: To Do, kind/bug
