### ISSUE TITLE
Eliminate verifications error

### ISSUE THREAD

**Issue by lymychp** [edenlabllc/ehealth.api#4629] opened 2019-04-01 06:15 UTC
we have the same 32 errors every minute on the verification service
```
  "app": {
      "log": "GenStateMachine #PID<0.4800.24> terminating\n** (ErlangError) Erlang error: {:bad_action_from_state_function, {:reply, :undefined, {:error, :timeout}}}\n    (stdlib) gen_statem.erl:1290: :gen_statem.parse_actions_reply/7\n    (stdlib) gen_statem.erl:1206: :gen_statem.loop_event_actions_list/10\n    (ssl) tls_connection.erl:133: :tls_connection.init/1\n    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3",
      "severity": "ERROR",
      "sourceLocation": {
        "file": "gen_statem.erl",
        "line": 1895,
        "function": "gen_statem.error_info/5"
      }
    },
    "request_id": null,
    "tag": "otp-verification-scheduler",
    "@timestamp": "2019-04-01T06:12:21.743647973+00:00"
  },
```

**Comment by AlexKovalevych** [comment] 2019-04-02 07:28
Duplicate of https://github.com/edenlabllc/ehealth.api/issues/4612

**Closed** 2019-04-02 07:28 UTC
Labels: [zube]: To Do, kind/bug
