### ISSUE TITLE
on-premise DC Performance test - pilot

### ISSUE THREAD

**Issue by lymychp** [edenlabllc/ehealth.api#1906] opened 2018-03-06 07:33 UTC
Develop and run test scripts  to check:

1. API: check at least 3 endpoints: no auth, with auth, with DS. Should get the same performance results as on GCS
2. Minio file storage: read/write performance

**Comment by gmile** [comment] 2018-03-14 16:19
Tested `minio`:

* Copying to minio:

    ```
    dd if=/dev/zero of=/tmp/minio-testing/capitation-report-sample bs=1m count=1
    for i in (seq 100); mc rm denovo/testing-upload/capitation-report-sample-$i; end
    mc cp /tmp/minio-testing/* denovo/testing
    ```

    Result:
    ```
    Total: 101.00 MB, Transferred: 100.13 MB, Speed: 5.40 MB/s
    ```

* Copying from minio:

    Perform copying to minio, then:

    ```
    mkdir /tmp/minio-testing-2
    mc cp denovo/testing /tmp/minio-testing-2/
    ```

    Result:

    ```
    Total: 100.00 MB, Transferred: 100.00 MB, Speed: 7.61 MB/s
    ```

**Comment by gmile** [comment] 2018-03-16 10:26
Some testing stats so far:

* 20 requests / second for declaration request creation

**Comment by gmile** [comment] 2018-03-16 10:27
@vsirius @AlexKovalevych let's please add comments with further testing results

**Comment by AlexKovalevych** [comment] 2018-03-16 10:31
is this a duplicate of https://github.com/edenlabllc/ehealth.api/issues/1907 ?

**Comment by gmile** [comment] 2018-03-16 13:29
@AlexKovalevych looks like so

**Comment by lymychp** [comment] 2018-03-16 13:33
not really. Scope of This task:
1) re-run the same tests that we have performed on the GCS using existing test scripts. Should get the same performance results as on GCS
2) Test performance of Minio file storage: read/write performance

#1907 - new test of the declaration creation.

**Comment by lymychp** [comment] 2018-04-03 12:46
@AlexKovalevych please add the latest test results

**Comment by gmile** [comment] 2018-04-12 14:09
I think we can close this, since migration has already happened.

**Closed by gmile** 2018-04-12 14:09 UTC
Labels: epic/infra, kind/task, project/DC migration, status/todo
