### ISSUE TITLE
unable to view all declarations

### ISSUE THREAD

**Issue by pzhuk** [edenlabllc/ehealth.api#1305] opened 2017-10-20 21:38 UTC
1) Login with the portal, selecting "Declrations to review" - only 2 declarations are shown (while 72 were registered already)

2) Click "Declarations", 5 are shown - select  "Show by 20" or "Show by 50" - nothing happens. Press F5 to page refresh - internal server error

**Comment by lymychp** [comment] 2017-10-30 06:58
1. @svetavedmed please test and try to reproduce on demo
2. @pzhuk related to pagination. Fixed on demo.

**Comment by svetavedmed** [comment] 2017-10-30 08:46
All declarations are shown on demo

**Comment by lymychp** [comment] 2017-11-06 15:19
@pzhuk it looks like it works on demo.

**Closed** 2017-11-13 15:14 UTC
Labels: bug, epic/NHS_admin_portal, kind/support, status/test
